hf_model_name = "openai-community/gpt2"
project = "debug_150m_zero_band"
type_model = "gpt2"

[train]
micro_bs = 16 # change this base on the gpu
reshard_after_forward = false

[optim]
batch_size = 512
warmup_steps = 500
total_steps = 8192

[diloco]
inner_steps = 5

[optim.optim]
lr = 4e-4
