name_model = "Qwen/Qwen2.5-0.5B"
project = "qwen2_0.5B"
metric_logger_type = "dummy"
type_model = "qwen2"

[train]
micro_bs = 8
fsdp_cpu_offload = true

[optim]
batch_size = 16
warmup_steps = 10
total_steps = 4

[optim.optim]
lr = 7e-4

[data]
seq_length = 1024
dataset_name_or_paths = "datasets/fineweb-edu"

[diloco]
inner_steps = 5

[ckpt]
interval = 5
path = "/home/lei/git/prime/qwen2_0.5B_ckpt"
